default_install_hook_types = ["pre-push"]
default_stages = ["pre-push"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt --all --check"
pass_filenames = false
files = "\\.rs$"
stages = ["pre-push"]
